name: kezilabda_statisztika
description: Kézilabda mérkőzés Statisztika - Simontornya KK LU14 2025
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+4
  path: ^1.8.0
  intl: ^0.17.0
  path_provider: ^2.0.11
  flutter_localizations:
    sdk: flutter
  fl_chart: ^0.60.0
  excel: ^2.0.0
  pdf: ^3.8.1
  printing: ^5.9.0
  file_picker: ^5.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
